SELECT GETTOTALDELIVERYFEES('3344556677') as CUSTOMER_FEES
from SYSIBM.SYSDUMMY1;

SELECT GETTOTALEMPLOYEESCOUNT() as OFFICES_EMPLOYEES
from SYSIBM.SYSDUMMY1;

SELECT GETAVERAGESERVICERATING() as DELIVERY_RATING_AVG
from SYSIBM.SYSDUMMY1;

SELECT *
FROM TABLE(GETCUSTOMERNAMESANDADDRESSES('3344556677')) as T;