--1
CREATE OR REPLACE FUNCTION GetTotalDeliveryFees(UCN CHAR(10))
RETURNS INTEGER
DETERMINISTIC
BEGIN
    DECLARE totalFees INTEGER;

    SELECT SUM(DELIVERY_FEE)
    INTO totalFees
    FROM Packages
    WHERE RECEIVER_UCN = UCN;

    IF totalFees IS NULL THEN
        SET totalFees = 0;
    END IF;

    RETURN totalFees;
END;


--2
CREATE OR REPLACE FUNCTION GetAverageServiceRating()
RETURNS DOUBLE
DETERMINISTIC
BEGIN
    DECLARE avgRating DOUBLE;

    SELECT SUM(SERVICE_RATING) / (COUNT(*) * 1.0)
    INTO avgRating
    FROM DeliveryWorkers;

    IF avgRating IS NULL THEN
        SET avgRating = 0;
    END IF;

    RETURN avgRating;
END;

--3

CREATE OR REPLACE FUNCTION GetTotalEmployeesCount()
RETURNS INTEGER
BEGIN
    DECLARE totalEmployeesCount INTEGER DEFAULT 0;

    SELECT SUM(OFFICES.EMPLOYEES_CNT) INTO totalEmployeesCount
    FROM OFFICES;

    RETURN totalEmployeesCount;
END;

--4
CREATE OR REPLACE FUNCTION FN24_8MI0400006.GetCustomerNamesAndAddresses(UCN_IN CHAR(10))
RETURNS TABLE (
    CUSTOMER_NAME VARCHAR(50),
    CUSTOMER_LAST_NAME VARCHAR(50),
    CUSTOMER_ADDRESS VARCHAR(100),
    CUSTOMER_NUMBER CHAR(12)
)
RETURN
    SELECT FIRST_NAME AS CUSTOMER_NAME,
           LAST_NAME AS CUSTOMER_LAST_NAME,
           ADDRESS AS CUSTOMER_ADDRESS,
           PHONE_NUMBER AS CUSTOMER_NUMBER
    FROM Customers
    WHERE CUSTOMERS.UCN = UCN_IN;

