set schema FN24_8MI0400006;

--1
CREATE VIEW PackageDetails AS
SELECT P.PACKAGE_ID,
       P.DELIVERY_ADDR,
       P.ESTIMATED_DELIVERY,
       P.DELIVERY_STAT,
       P.DELIVERY_FEE,
       P.COURSE_ID,
       P.WORKER_ID,
       P.OFFICE_NUMBER,
       P.DATE_COLLECTED,
       P.DATE_SENT,
       P.RECEIVER_UCN,
       P.SENDER_UCN,
       C_SENDER.FIRST_NAME AS SENDER_FIRST_NAME,
       C_SENDER.LAST_NAME AS SENDER_LAST_NAME,
       C_RECEIVER.FIRST_NAME AS RECEIVER_FIRST_NAME,
       C_RECEIVER.LAST_NAME AS RECEIVER_LAST_NAME
FROM Packages P
JOIN Customers C_SENDER ON P.SENDER_UCN = C_SENDER.UCN
JOIN Customers C_RECEIVER ON P.RECEIVER_UCN = C_RECEIVER.UCN;

--2
CREATE VIEW WorkerOfficeDetails AS
SELECT DW.WORKER_ID,
       DW.YEARS_EXP,
       DW.FIRST_NAME,
       DW.SERVICE_RATING,
       DW.SALARY,
       DW.OFFICE_NUMBER,
       O.ADDRESS AS OFFICE_ADDRESS,
       O.EMPLOYEES_CNT AS OFFICE_EMPLOYEES_COUNT,
       O.CITY_LOCATION AS OFFICE_CITY,
       O.OFFICE_RATING
FROM DeliveryWorkers DW
JOIN Offices O ON DW.OFFICE_NUMBER = O.OFFICE_NUMBER;
